### PR TITLE
Feat/vd 4731 update tap oauth config

### PR DESCRIPTION
**Pull request by hd-o**
https://villagelabs.atlassian.net/browse/VD-4731

### CODE REVIEW

**Comment by martin-village** [comment]
fyi this shouldn't do anything, because this meltano.yml is only here for test purpose

**Review by AJWurts — APPROVED** [review]

**Comment by AJWurts** [comment]
@villagelabsco

**Comment by AJWurts** [comment]
@villagelabsco

**Comment by martin-village** [comment]
# villagelabsco/tap-hubspot #11

## Change Summary:
- Added a new GitHub Actions workflow for Dependabot vulnerability checks
- Updated `meltano.yml` to include new settings for client credentials
- Modified `auth.py` to support environment variables for client credentials
- Updated `client.py` to use environment variables for authentication

## Potential Vulnerabilities:
- File: `.github/workflows/dependabot.yaml:41`
- Code: ```echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token```
- Explanation: Exposing secrets in command line arguments can be risky as they might be logged or visible in process lists.

- File: `tap_hubspot/auth.py:16-18`
- Code:
```python
env_client_id = os.getenv("TAP_HUBSPOT_CLIENT_ID")
env_client_secret = os.getenv("TAP_HUBSPOT_CLIENT_SECRET")
env_refresh_token = os.getenv("TAP_HUBSPOT_REFRESH_TOKEN")
```
- Explanation: While using environment variables for secrets is generally good practice, ensure that these environment variables are properly secured and not accidentally exposed in logs or error messages.

## Code Smells:
- File: `tap_hubspot/auth.py:19-23`
- Code:
```python
return {
    "client_id": self.config["client_id"] or env_client_id,
    "client_secret": self.config["client_secret"] or env_client_secret,
    "grant_type": "refresh_token",
    "refresh_token": self.config["refresh_token"] or env_refresh_token,
}
```
- Explanation: The use of the `or` operator for fallback values could lead to unexpected behavior if the config values are empty strings or falsy values. Consider using a more explicit fallback mechanism.

## Debug Logs:
- File: `.github/workflows/dependabot.yaml:57`
- Code: ```echo "Alerts: $alerts"```
- Explanation: This debug log might expose sensitive information about vulnerabilities. Consider removing or obfuscating this log in production.

## Unintended Consequences:
- File: `tap_hubspot/client.py:55-56`
- Code:
```python
env_refresh_token = os.getenv("TAP_HUBSPOT_REFRESH_TOKEN")
if is_oauth_credentials(self.config) or env_refresh_token:
```
- Explanation: The addition of the `env_refresh_token` check might cause the OAuth authenticator to be used even when not intended, if the environment variable is set but the config is not using OAuth.

- File: `meltano.yml:17-18`
- Code:
```yaml
- name: client_id
  kind: string
- name: client_secret
  kind: password
```
- Explanation: Adding these new settings without proper documentation or migration guide might break existing configurations or cause confusion for users upgrading the tap.

## Risk Score: 6

**Pull request merged**
